CardMarket_Web_Core/Models/ApiQueryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CardMarket_Web_Core.Models
{
    public class ApiQueryModel
    {
        // Used by view to ensure Model has data
        /// https://stackoverflow.com/questions/8448778/mvc3-razor-how-to-check-if-model-is-empty
        public bool Empty
        {
            get { return orders.Count == 0; }
        }

        public List<Order> orders = new List<Order>();

        public ApiQueryModel()
        {

        }
    }
}

CardMarket_Web_Core/Models/ErrorViewModel.cs
using System;

namespace CardMarket_Web_Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CardMarket_Web_Core/Models/Input.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CardMarket_Web_Core.Models
{
    public class Input
    {
        [Required]
        [DisplayName("Card Names:")]
        public string cardNamesString { get; set; }

        [DisplayName("Country Code:")]
        public string countryCode { get; set; }
        public bool singleCountryOnly;

        public List<string> cardNamesList;

        public Input(List<string> _listCardNames, string _countryCode = "")
        {
            countryCode = _countryCode;
            singleCountryOnly = (countryCode != "");
        }

        public Input(string _listCardNames, string _countryCode = "")
        {
            countryCode = _countryCode;
            singleCountryOnly = (countryCode != "");
        }

        public void PrepareInput()
        {
            cardNamesString = cardNamesString.Replace("\r\n", ",");
            cardNamesString = cardNamesString.Trim(',');

            ///https://stackoverflow.com/questions/2235683/easiest-way-to-parse-a-comma-delimited-string-to-some-kind-of-object-i-can-loop
            cardNamesList = cardNamesString.Split(',').Select(sValue => sValue.Trim()).ToList();

            /// https://stackoverflow.com/questions/3069748/how-to-remove-all-the-null-elements-inside-a-generic-list-in-one-go
            cardNamesList.RemoveAll(item => item == "");

            if (countryCode == null)
            {
                singleCountryOnly = false;
            }
            else
            {
                countryCode = countryCode.ToUpper();
                singleCountryOnly = (countryCode != "");
            }
        }

        public Input()
        {
        }
    }
}

CardMarket_Web_Core/Models/Order.cs
using CardMarket_Web_Core.ApiQueryLogic;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CardMarket_Web_Core.Models
{
    public class Order
    {
        [DisplayName("Seller:")]
        public string user { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2} €")]
        [DisplayName("Total Cost:")]
        public float totalCost { get; set; }

        [DisplayName("Articles:")]
        public List<Article> articles { get; set; }

        [DisplayName("Shipping Location:")]
        public string sellerLocation { get; set; }

        public Order()
        {
            articles = new List<Article>();
            sellerLocation = "";
        }
    }

    public class Article
    {
        // metaproduct ID added by me not in 
        // returned Article JSON data
        public int idMetaproduct { get; set; }
        public string enName { get; set; }
        public int idArticle { get; set; }
        public int idProduct { get; set; }

        public string comments { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2} €")]
        [DisplayName("Price:")]
        public float price { get; set; }
        public Seller seller { get; set; }
        public int idCurrency { get; set; }
        public string currencyCode { get; set; }
        public int count { get; set; }
        public bool inShoppingCart { get; set; }
        public string condition { get; set; }
        public bool isFoil { get; set; }
        public bool isSigned { get; set; }
        public bool isPlayset { get; set; }
        public bool isAltered { get; set; }
    }
}

CardMarket_Web_Core/Controllers/CardMarketController.cs
using CardMarket_Web_Core.ApiQueryLogic;
using CardMarket_Web_Core.DbCode;
using CardMarket_Web_Core.Exceptions;
using CardMarket_Web_Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using static CardMarket_Web_Core.ApiQueryLogic.APIQuery;

namespace CardMarket_Web_Core.Controllers
{
    public class CardMarketController : Controller
    {
        readonly IConfiguration config;
        private readonly IDAO iDAO;

        public CardMarketController(IConfiguration _config)
        {
            config = _config;
            string env = config["ENV"];
            string connectionString =  config.GetConnectionString("DefaultConnection");

            if (env == "Pi")
            {
                iDAO = new DAOMySQL(connectionString); 
            }
            else
            {
                iDAO = new DAOSQL(connectionString); 
            }
        }

        public IActionResult Index()
        {
            Input input = new Input
            {
                cardNamesString = "Shadowborn Apostle"
            };

            return View("findsellers", input);
        }

        public string test()
        {
            return "test message";
        }

        public ActionResult ViewOrders(Input input)
        {
            try
            {
                input.PrepareInput();

                APIQuery query = new APIQuery(input);

                ApiQueryModel apiQueryModel = new ApiQueryModel
                {
                    orders = query.RunQuery(iDAO)
                };

                return View("ViewOrders", apiQueryModel) ;
            }
            catch (AggregateException ae)
            {
                /// https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-handle-exceptions-in-parallel-loops
                foreach (var ex in ae.Flatten().InnerExceptions)
                {

                    if (ex is WebException)
                    {
                        //ViewBag.ErrorTitle = "CardMarket Error" + ex.GetType();
                        ViewBag.ErrorMessage = "CardMarket's API is not available, returning Dummy data for demonstrative purposes.";

                        List<Article> a = new List<Article>()
                        {
                            new Article{ enName = "Damnation", price = 1.1f, currencyCode = "GB"},
                            new Article{ enName = "Kadena",    price = 2.2f, currencyCode = "GB"},
                            new Article{ enName = "Volrath",   price = 3.3f, currencyCode = "GB"},
                        };
                        List<Order> o = new List<Order>
                        {
                            new Order{user = "seller 1", totalCost = 111f,articles = a},
                            new Order{user = "seller 2", totalCost = 222f,articles = a},
                            new Order{user = "seller 3", totalCost = 333f,articles = a}
                        };
                        ApiQueryModel apiQueryModelDummy = new ApiQueryModel
                        {
                            orders = o
                        };


                        return View("ViewOrders", apiQueryModelDummy);

                        //return View("Error");
                    }
                    
                    else if (ex is CardNotFoundException)
                    {
                        ViewBag.ErrorTitle = "Card Name";
                        ViewBag.ErrorMessage = ex.Message;
                        return View("Error");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                return View("Error");
            }
        }
    }
}

CardMarket_Web_Core/Views/CardMarket/ApiQuery.cshtml
@model CardMarket_Web_Core.Models.Input

@{
    ViewData["Title"] = "ApiQuery";
}

<h1>Find Sellers</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ViewOrders">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="cardNamesString" class="control-label"></label>
                <textarea asp-for="cardNamesString" class="form-control" style="height:6em;"  onkeyup="autoGrow(this);"></textarea>
                <span asp-validation-for="cardNamesString" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="countryCode" class="control-label"></label>
                <input asp-for="countryCode" class="form-control" />
                <span asp-validation-for="countryCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        
        function autoGrow(oField)
        {
            if (oField.scrollHeight > oField.clientHeight)
            {
                oField.style.height = oField.scrollHeight + "px";
            }
        }
    </script>
}

CardMarket_Web_Core/Views/CardMarket/FindSellers.cshtml
@model CardMarket_Web_Core.Models.Input

@{
    ViewData["Title"] = "Find Sellers";
}

<h1>Find Sellers</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ViewOrders">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="cardNamesString" class="control-label"></label>
                <textarea asp-for="cardNamesString" class="form-control" style="height:6em;"  onkeyup="autoGrow(this);"></textarea>
                <span asp-validation-for="cardNamesString" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="countryCode" class="control-label"></label>
                <input asp-for="countryCode" class="form-control" />
                <span asp-validation-for="countryCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        
        function autoGrow(oField)
        {
            if (oField.scrollHeight > oField.clientHeight)
            {
                oField.style.height = oField.scrollHeight + "px";
            }
        }
    </script>
}

CardMarket_Web_Core/Views/CardMarket/ViewOrders.cshtml
@model CardMarket_Web_Core.Models.ApiQueryModel
<p class="alert-warning">@ViewBag.ErrorMessage</p>
<div>
    <h4>Sellers Found</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @if (Model.Empty)
    {
    <h5>No Sellers found.</h5>
    }
    else
    {
        foreach (var item in Model.orders)
        {
    <table>
        <tr>
            <td>
                @Html.DisplayNameFor(model => item.user)
            </td>
            <td>
                @Html.DisplayFor(model => item.user)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => item.totalCost)
            </td>
            <td>
                @Html.DisplayFor(model => item.totalCost)
            </td>
        </tr>
        <tr>
            <td class="right-margin">
                @Html.DisplayNameFor(model => item.sellerLocation)
            </td>
            <td>
                @Html.DisplayFor(model => item.sellerLocation)
            </td>
        </tr>

        <tr>
            <td style="vertical-align: top">
                @Html.DisplayNameFor(model => item.articles)
            </td>
            <td>
                <table>
                    @foreach (var article in item.articles)
                            {
                    <tr>
                        <td class="right-margin">
                            @Html.DisplayFor(model => article.enName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => article.price)
                        </td>
                    </tr>
                            }
                </table>
            </td>
        </tr>
    </table>

    <hr />
        }
    }

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CardMarket_Web_Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CardMarket_Web_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CardMarket" asp-action="Index">Find Sellers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - JP
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>